### this param file has been copied from last year's group 2
### ekf config file ###
ekf_filter_node:
    ros__parameters:
        two_d_mode: True
        world_frame: odom
        base_link_frame: base_link
        
        publish_tf: true

        use_control: False

        control_config: [ True, True, False,
            False, False, True]

        imu0: /robot/imu/value
        imu0_remove_gravitational_acceleration: True
        imu0_config: [
            false,  false,  false,
            false, false, false,
            false,  false, false,
            false, false, true,
            true, true, false
        ]
        imu0_relative: False
        imu0_differential: True

        odom0: /robot/speed/value
        odom0_config: [
            false,  false,  false,
            false, false, false,
            true,  true, false,
            false, false, true,
            false, false, false
        ]
        odom0_relative: True
